name: Publish Java

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version: `X.X.X`"
        required: true
        default: '1.0.0'
        type: string

jobs:
  publish:
    name: Publish Java
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Download native libraries
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: all-java-libraries
          commit: ${{ github.sha }}
          path: java/src/main/resources

      - run: cd java/src/main/resources/osx;ls

      - name: Build Java
        working-directory: java
        run: ./gradlew jar
      
      - uses: actions/upload-artifact@v3.1.1
        with:
          name: TrajoptLib-jar
          path: java/build/libs/*.jar

      # - name: Publish package
      #   run: ./gradlew publishMavenPublicationToGithubRepository -Pplatform_id=${{ matrix.platform_id }} -PgithubUsername=$GITHUB_ACTOR -PgithubPassword=${{ secrets.GITHUB_TOKEN }}
 